name: Merge to Main

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20, 22]

    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v4
      - name: Run unit tests
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run lint
